Current book refactor
CS495Group8/ByItsCover pull request #13
Opened 2021-03-23 20:34 UTC by jrodonohue

Refactored cofe and integrated scrapers

2021-03-23 22:18 UTC, mtuthill requested changes
Great job with everything! You write some really clean code. The response time for the scraping is awesome and quick. Some overall comments:

- [ ] It doesn't seem that the previous button is still working from the final review/rating listing page to go back to the main page
- [ ] I tested a couple of search by title queries but the glass hotel information is showing up, not the book I searched for

2021-03-23 23:43 UTC, RipleyRyan commented
I don't have much other to comment on, it seems like Marc covered all the important things. Nice work on this though Jack it looks very solid. Excited to get this merged up.

2021-03-24 01:34 UTC, jrodonohue commented on app/src/main/java/com/example/byitscover/scrapers/BarnesAndNobleScraper.java
> +                new Book(query.getTitle(), query.getAuthor(), null, null),
I didn't find any extraction of the author or title of the search result in the Barnes and Noble scraper, so I just used the query title.

2021-03-24 01:35 UTC, jrodonohue commented on app/src/main/java/com/example/byitscover/scrapers/GoodreadsScraper.java
> +                new Book(query.getTitle(), query.getAuthor(), null, null),
I copied and pasted my Barnes and Noble code, and I overlooked this. I've fixed this, but I still need to commit.

2021-03-24 01:37 UTC, jrodonohue commented on app/src/test/java/com/example/byitscover/scrapers/GoodreadsScraperTest.java
>      @Before
Removed the file from the branch

2021-03-24 01:41 UTC, jrodonohue commented on app/src/main/java/com/example/byitscover/ReviewPage.java
> +            }
Removed duplicate

2021-03-24 02:06 UTC, jrodonohue commented on app/src/main/java/com/example/byitscover/ReviewPage.java
> +            // Display
The code is required to handle these exceptions by Java, but these exceptions should never occur. I updated the code to throw an `AssertionError` if any of the exceptions occur.

2021-03-24 02:10 UTC, jrodonohue commented on app/src/main/java/com/example/byitscover/ReviewPage.java
>          setAverageRatingValue(view);
This is to initialize the book display with a default book, but I'm not sure why it uses goodreadsResult. The code has been fixed to use the default book.

2021-03-24 02:25 UTC, jrodonohue commented on app/src/main/java/com/example/byitscover/ReviewPage.java
> +        });*/
Removed!

2021-03-24 02:28 UTC, jrodonohue commented on app/src/main/java/com/example/byitscover/helpers/Isbn.java
> +// TODO: Add unit tests
I already added unit tests, and I forgot to remove this. Thanks for pointing it out!

2021-03-24 02:42 UTC, mtuthill commented on app/src/main/java/com/example/byitscover/scrapers/BarnesAndNobleScraper.java
> +                new Book(query.getTitle(), query.getAuthor(), null, null),
Yeah definitely open to discussion on how we want to deal with populating the title and author on the review page moving forward. I think it should come from one of the scrapers to act as a bit of the spell check, but I'm not sure how to choose which one we go with. Maybe when we implement the "choose one of these 3 books" pop-up thing, we can use whatever info is actually selected by the user. I just think if we leave it just using the query we'll have misspellings/missing capitalization/gibberish that is outputted from the OCR. So I think let's leave this as is but for now just use the Goodreads results to populate the title and author and investigate further next week.

2021-03-24 02:42 UTC, mtuthill commented on app/src/main/java/com/example/byitscover/scrapers/BarnesAndNobleScraper.java
> +                new Book(query.getTitle(), query.getAuthor(), null, null),
Just some things for all of us to think about

2021-03-25 01:00 UTC, mtuthill approved these changes

2021-03-25 01:33 UTC, merged